### ISSUE TITLE
Start the game after all players are in the room

### ISSUE THREAD

**Issue by elBeato** [sopra-fs22-group-36/screw-your-neighbor-react#19]
The game is stored with all players. Afterwards the players are ready to see the cards. 

Estimated time: 4h

https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/5

**Comment by MorisCamporesi** [comment]
Button to start the game  (including the a validation that there are > 1 players present ) was implemented in Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/47
Functionality that everyone in the lobby joins the same game after start was implemented in issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/29
Backend functionality was implemented in Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/55
