### ISSUE TITLE
Announce how many tricks the player will win 

### ISSUE THREAD

**Issue by elBeato** [sopra-fs22-group-36/screw-your-neighbor-react#31]
Belongs to each match, a match consists of 1 up to 5 rounds. Before each match the player can announcing when locking on this cards, how many tricks she or he will win. 

## Estimated time
 4h

## User story
https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/8

**Comment by MorisCamporesi** [comment]
This issue was later reworked in: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/64
