### ISSUE TITLE
Players can only play cards with anybody of the match did the score annoucing

### ISSUE THREAD

**Issue by elBeato** [sopra-fs22-group-36/screw-your-neighbor-react#59]
Insert aswell a dialog window to inform the player whats going on. 

## Estimated time: 
4h

**Comment by MorisCamporesi** [comment]
- Players can now only announce their score when their match state is "playing": https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/pull/60
- Players can now only play their cards when their match state is "playing": https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/69
