### ISSUE TITLE
Add functional invite button

### ISSUE THREAD

**Issue by MorisCamporesi** [sopra-fs22-group-36/screw-your-neighbor-react#91]
When klicking this button:

> a list of registered users is shown, one can invite people from that list

or

> a link is copied to the clipboard and when registered used this link the user gets forwarded directly to the room

## Estimate time: 
16h

## Priority: 
high

**Comment by MorisCamporesi** [comment]
@BacLuc 
Ich han versuecht mal chli wiiterzmache, han aber s gfühl ich verkompliziere da Sache und bin generell chli ufem holzweg will ich eusi api nanig ganz so dusse han. Wär happy wenn'd mer viellicht es feedback dezue chönntisch gäh!

**Comment by BacLuc** [comment]
@MorisCamporesi 
i made a draft PR of your changes and added comments.
I hope this helps
