### ISSUE TITLE
Add registering / log-in view

### ISSUE THREAD

**Issue by MorisCamporesi** [sopra-fs22-group-36/screw-your-neighbor-react#92]
Based on user story: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/14

**Comment by BacLuc** [comment]
Depends on closing userstory https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/14 this one is obsolet.
Information to https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/14

We are closing this issue without an implementation. The reasons are varied:

No added value for the fun of the game
Heroku does not have a persistent DB
All common games in this form are played without registration.
We have already implemented user account login and registration in M1.
Low priority

It took place in consultation with our TA.
