### ISSUE TITLE
create a user-page view

### ISSUE THREAD

**Issue by MorisCamporesi** [sopra-fs22-group-36/screw-your-neighbor-react#94]
Based on user story: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/15
> -  On the main user page is button to see my performance.
> -  When the player is logged in, he has the option of clicking on his profile which opens a window that lets him see his game performance (minimum: Games won, games lost) and important account information (minimum: username and Creation date).

**Comment by elBeato** [comment]
Invalid, while #14 and #15 closed. Further information there.
