### ISSUE TITLE
Bugfix Allow for scrolling in Lobby

### ISSUE THREAD

**Issue by CarmenUZH** [sopra-fs22-group-36/screw-your-neighbor-react#96]

**Comment by MorisCamporesi** [comment]
Probably not needed as with PR: https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/pull/86 the rooms that have started will not be displayed anymore

**Comment by CarmenUZH** [comment]
e58f18136cddc2bdc6d7f39fc9faa0358ddca590

**Comment by CarmenUZH** [comment]
The Demo presentation has shown us, that we need to make our game more immune to trolls, who would just create endless rooms but never start them to mess with other players
This is why this bugfix is still important

**Comment by MorisCamporesi** [comment]
> The Demo presentation has shown us, that we need to make our game more immune to trolls, who would just create endless rooms but never start them to mess with other players This is why this bugfix is still important

Good Point!
